x-motemen/git-pr-release

- README.md
- bin/git-pr-release
Hi, thank you for creating useful tool.
I'd like to introduce different exit status codes for errors.
Now git-pr-release always exit with status code 1 if some error happens.
We run git-pr-release from Jenkins job, so if "No pull requests to be released", the build marks as failure.
It'd be nice if we can distinguish the reason of error from wrapper script - imagine this shell script is put as "Build shell script" text area of Jenkins job configuration page.
```bash
#!/bin/bash
echo $(git-pr-release)
if [ $? == 1 ]
then
exit 0
else
exit $?
fi
```
> Use different exit status code for errors

- README.md
- bin/git-pr-release
I implemented new feature to add specific labels for the release-PR.
Developers can set labels list in .git-pr-release like following way.
```
[pr-release]
labels = "git-pr-release,New Feature"
```
Please review me. :bow:
> Implement feature to add labels to a release-PR.

- bin/git-pr-release
This PR let us use information of changed files in the specified erb template.
I want to add checklists to release flow by changed files information.  For example, if `script/onetime/*` are updated, I want to add a checklist to exec these.  We can do it by the following code if changed files are passed to the erb template.
```
<%- if changed_files.any?{|f| f.filename.match(%r{^script/onetime/}) } -%>
<% changed_files.select{|f| f.filename.match(%r{^script/onetime/}) }.each do |file| %>
<% end %>
<%- end -%>
```
> Fetch release PR files to use in erb template

- bin/git-pr-release
We're going to run this script from external CI service (i.e. wercker), which cannot access the private repo with local git command.
So we should or disable `git remote update origin` of this script, or grant access to the repo manually.
The former one seems handy..! This PR implements it!
> Add --no-fetch option

- bin/git-pr-release
In my project, github pr assignee is just reviewer. So we want to see auther names on release PR's description, instead of assignee names.
Mentioned users of listed PRs are decided according to following priority.
1. assignee
2. author
Add new mode `mention-type: author` that mentions to author.
- Add new git config record `pr-release.mention-type`
- When it is set to `author`, git-pr-release write PR auther name for mention
```
git config pr-release.mention-type author
```
> [proposal] Create `mention-type` configuration

- README.md
- bin/git-pr-release
> Support `GIT_PR_RELEASE_TEMPLATE` and `GIT_PR_RELEASE_LABELS` environment variables

- bin/git-pr-release
Fix #27
`gem install` puts the executable file in `$GEM_HOME/bin/git-pr-release` .
This executable file makes version switching.
```sh
$ git-pr-release _1.6.0_
```
And the code to version switching is below.
```ruby
load Gem.activate_bin_path('git-pr-release', 'git-pr-release', version)
```
So `if $0 == __FILE__` idiom does not work.
> Fix: released git-pr-release do nothing

- exe/git-pr-release
- git-pr-release.gemspec
- lib/git/pr/release.rb
- lib/git/pr/release/cli.rb
- lib/git/pr/release/util.rb
- spec/git/pr/release_spec.rb
- spec/spec_helper.rb
Ref: https://github.com/motemen/git-pr-release/issues/29
I also got the same issue as https://github.com/motemen/git-pr-release/issues/29. (Our CI server uses rbenv.)
```rb
main if $0 == __FILE__ || $0 == File.join(Gem.dir, "bin", "git-pr-release")
```
I tried to fix this code, but at the end, I also have come to the same conclusion with @hkurokawa.
>So I am wondering if there might be no way to tell apart script loading from script execution (as rbenv loads the script to run).
I think this is one of the ways to fix current situation. My motivation is just to make this script work properly. Basically I tried to not change any logic. 
```
gem build git-pr-release.gemspec
gem uninstall git-pr-release
gem install /path/to/git-pr-release/git-pr-release-0.8.0.gem
git-pr-release
```
> Extract logic from bin/git-pr-release

- lib/git/pr/release/util.rb
List pull requests files API in Github API returns 30 items by default.  So we cannot fetch all changed files if release pull request is large.
- https://developer.github.com/v3/#pagination
- https://developer.github.com/v3/pulls/#list-pull-requests-files
This PR fix to fetch changed files as many as possible
> Fetch changed files as many as possible

- lib/git/pr/release/util.rb
`host`, `repository`, and `scheme` are not used.
> Remove unused

- lib/git/pr/release/cli.rb
- lib/git/pr/release/util.rb
- spec/git/pr/release/cli_spec.rb
- spec/git/pr/release_spec.rb
* CLI#start as instance method
* Split methods
- configure
- fetch_merged_prs
- create_release_pr
- detect_existing_release_pr
- prepare_release_pr
- build_and_merge_pr_title_and_body
- update_release_pr
* Move Util#pull_request_files to CLI
* Move evaluating `template_path` by CLI#configure from Util#build_pr_title_and_body
> Refactor CLI

- lib/git/pr/release/cli.rb
- spec/git/pr/release/cli_spec.rb
GitHub API has `head` and `base` option.
https://developer.github.com/v3/pulls/#list-pull-requests
Prefer using search criteria to finding in a loop.
> Use API option when detecting existing release PR

- lib/git/pr/release/util.rb
Occurs for monorepo.
I implemented a bug with this commit: 2790e486f3
Fixes #46.
> Fix Errno::ENOENT when finding the specified template

- lib/git/pr/release/cli.rb
GitHub API list-pull-requests によると、
https://developer.github.com/v3/pulls/#list-pull-requests
> Filter pulls by head user or head organization and branch name in the format of user:ref-name or organization:ref-name. For example: github:new-script-format or octocat:test-branch.
`head` には `head user or head organization` が必須であったようで、 `base` のみで絞り込まれている。
このため、`base == production_branch` のPRが複数存在している場合に、取得したPRが、 `head == staging_branch` であることもあれば、`head != staging_branch` であることもあり、意図しないPRを git-pr-release が更新することがある。
`head` パラメータをAPI仕様どおり指定することで、本来あるべきだった挙動にする。
> List PR API needs head user or head organization and branch name

- README.md
- lib/git/pr/release/pull_request.rb
- right now it has to be git config
- adds an environment variable as an option to set this to author
- updates readme to surface this config
> support `GIT_PR_RELEASE_MENTION` environment variable

- lib/git/pr/release/util.rb
Because ERB changed how to handle initialization arguments since Ruby 2.6.0, it warns `lib/git/pr/release/util.rb` 's usage.
```
/Users/ohbarye/.ghq/github.com/ohbarye/git-pr-release/lib/git/pr/release/util.rb:97: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/Users/ohbarye/.ghq/github.com/ohbarye/git-pr-release/lib/git/pr/release/util.rb:97: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
Ruby commit: https://github.com/ruby/ruby/commit/cc777d09f44fa909a336ba14f3aa802ffe16e010
Rubocop's handling: https://github.com/rubocop-hq/rubocop/pull/5614/files
Run `rspec` with v2.6.0 or above.
There're warnings …
> Suppress warning for ERB

- spec/spec_helper.rb
Without this change, on docker image `ruby:2.5.8` fails running tests
```
1) Git::Pr::Release#build_pr_title_and_body without template_path is expected to eq "Release 2019-02-20 22:58:35 +0900"
Failure/Error: expect(pr_title).to eq "Release 2019-02-20 22:58:35 +0900"
expected: "Release 2019-02-20 22:58:35 +0900"
got: "Release 2019-02-20 22:58:35 +0000"
(compared using ==)
```
> Make stable test with timezone

- lib/git/pr/release/cli.rb
> Add sleep because the search is repeated for the number of commits

- lib/git/pr/release/cli.rb
Hi,
It seems that when the squash option is used, the PR numbers all return `1`.
It has been occurring since #61 .
It seems to be because the return value of `sleep 1` is used in generating the array of PR numbers.
I was not able to add any test code, but I did confirm that the return value of the array map changes.
```ruby
irb(main):005:0> Array[1, 2, 3].map do |x|
irb(main):006:1* x
irb(main):007:1> sleep 1
irb(main):008:1> end
=> [1, 1, 1]
irb(main):009:0> Array[1, 2, 3].map do |x|
irb(main):010:1* sleep 1
irb(main):011:1> x
irb(main):012:1> end
=> [1, 2, 3]
```
> fix wrong pr number due to sleep

- lib/git/pr/release/pull_request.rb
This is because GitHub has been updated to automatically render the title of the Pull Request URL in the list item.
Close https://github.com/x-motemen/git-pr-release/issues/65
> Exclude titles from checklist items

- lib/git/pr/release/cli.rb
Fixed: https://github.com/x-motemen/git-pr-release/issues/67
I created a sample Pull Request what body is empty, and confirmed that returns nil with the sample code below.
This issue caused by GitHub API response is changed, but I could not confirmed this GitHub API changes is temporary or not.
sample pull request: 
https://github.com/w1mvy/git-pr-release/pull/1
```
(*'-') < cat sample.rb                                                                                   [~/go/src/github.com/w1mvy/sample-gh]
require "octokit"
client = Octokit::Client.new(:access_token => 'my-token')
pr = client.pull_request("w1mvy/git-pr-release", 1)
if pr.body == ''
puts "empty"
elsif pr.body == nil
puts "nil"
end
(*'-') < bundle exec ruby sample.rb …
```
> Add nil check for release_pr.body

- spec/git/pr/release_spec.rb
I resolved fail test in rspec.
related https://github.com/x-motemen/git-pr-release/issues/65
```
$ bundle exec rspec
...
Failures:
1) Git::Pr::Release#build_pr_title_and_body without template_path is expected to eq "- [ ] #3 Provides a creating release pull-request object for template @hakobe\n- [ ] #6 Support two factor auth @ninjinkun\n"
Failure/Error:
expect(new_body).to eq <<~MARKDOWN
MARKDOWN
expected: "- [ ] #3 Provides a creating release pull-request object for template @hakobe\n- [ ] #6 Support two factor auth @ninjinkun\n"
got: "- [ ] #3 @hakobe\n- [ ] #6 @ninjinkun\n"
(compared using ==)
Diff:
@@ -1,3 +1,3 @@
-- [ ] #3 Provides a creating release pull-request object for template @hakobe
-- [ ] #6 Support two factor auth @ninjinkun
+- [ ] #3 @hakobe
+- [ ] #6 @ninjinkun
Finished …
```
> [Spec] Fix spec for build_pr_title_and_body

- spec/git/pr/release/cli_spec.rb
- spec/git/pr/release_spec.rb
- spec/support/file_fixture_support.rb
closes https://github.com/x-motemen/git-pr-release/issues/72
Ruby 3.1.0 might include a breaking change using Psych v4 as default.
ref: https://bugs.ruby-lang.org/issues/17866
According to the issue on `bugs.ruby-lang.org`, it's not decided yet that Ruby 3.1.0 includes the change.
But even if Ruby 3.1.0 doesn't ship the change, it's nice to use `unsafe_load_file` explicitly for further breaking change, I think.
Tests passed on CI.
https://github.com/x-motemen/git-pr-release/runs/4560196751?check_suite_focus=true
> Use `YAML.unsafe_load_file` instead of `YAML.load_file`

- lib/git/pr/release/cli.rb
When executing `git-pr-release --squashed` option, each sha1 diff of staging and production is mapped to "To be Released" entry at the generated PR.  This results in duplicated entries if several sha1s belonged to single PR.
`uniq` the pr numbers and remove duplicates.
> remove duplicated PR entries at squash

- lib/git/pr/release/cli.rb
follow on #75
This allows us to avoid API Limit restrictions and reduce execution time.
The issue search API allows bulk requests with multiple SHA1s. This is difficult to read from the documentation, but GitHub support has responded that this is the spec.
> use bulk issue search to reduce API calls

- README.md
- lib/git/pr/release/cli.rb
closes #15
- Verify SSL certificate default
- Add `pr-release.ssl_no_verify` option to skip verifying SSL certificate
- Also Env `GIT_PR_RELEASE_SSL_NO_VERIFY` works
> Add option "ssl_no_verify" to skip verifying ssl certificate

- lib/git/pr/release/pull_request.rb
cf. #66
Add optional argument to `PullRequest#to_checklist_item` to print title of pull request.
It still isn't printed In default.
----
I know GitHub's markdown renders the title and state of issue/pullreq automatically:
> If you reference an issue, pull request, or discussion in a list, the reference will unfurl to show the title and state instead.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests
However, this feature is disabled in GitHub Enterprise Server for now (2022-03-01).
As proof of it, there is no description about automatically printed the title and state in doc.
https://docs.github.com/en/enterprise-server@3.4/get-started/writing-on-github/working-with-advanced-formatting/autolinke …
> add an argument to to_checklist_item to print pr title

- README.md
- lib/git/pr/release/cli.rb
closes #80 
#77 introduces new configuration `ssl_no_verify` in `git config`.
But git config does not allow to use underscore.
```console
$ git config pr-release.foo_bar
error: invalid key: pr-release.foo_bar
```
>  The variable names are case-insensitive, allow only alphanumeric characters and -, and must start with an alphabetic character. 
https://git-scm.com/docs/git-config#_configuration_file
To fix it, rename `ssl_no_verify` to `ssl-no-verify`.
> fix forbidden git config name (#80)

- spec/spec_helper.rb
octokit v4.23.0 changes to load Octokit::Client with autoload.
> Fix CI (uninitialized constant Sawyer)

- lib/git/pr/release/pull_request.rb
It is stressful to call out pr over and over when writing our templates as follows.
```erb
<% pull_requests.each do |pr| -%>
- #<%=  pr.pr.number %>
<% end -%>
```
So I resolved to use method_missing to delegate, even though it is rough.
I'm not a Ruby person, so I don't know if this is a good way. However, git-pr-release is just a tool, so I think having an easy interface like this is not a bad idea.
> delegate to @pr when method_missing in PullRequest

- README.md
The README describes exit status 2, 3, 4 for each error. But the code to return those statuses have disappeared at https://github.com/x-motemen/git-pr-release/commit/7afcbc47b0ffc36f4cdd69537b7e911948b8e191 and they are never returned since v1.2.0.
Therefore, I'd say the description on README is obsolete and should be updated.
> Remove exit statuses that are never returned

- lib/git/pr/release/cli.rb
- spec/git/pr/release/cli_spec.rb
git-pr-release requires git history. However, in many CI services in recent years, the shallow clone is used by default for speed. e.g., https://github.com/actions/checkout
It requires users to write additional settings such as `fetch-depth: 0`, which is a pitfall for beginners.
To make it easier to use, I add behavior to determine if a repository is a shallow repository and, if so, unshallow it.
It may be controversial whether this behavior is also applied when `--no-fetch` is specified. Still, I added this behavior uniformly since git-pr-release does not work correctly with a shallow clone.
`git fetch --unshallow` is available git 1.8.3 or later, and `git rev-parse --is-shallow-repository` is also 2.15. These are old enough, and in recent years, users have been using the newer git …
> unshallow if a shallow repository

- lib/git/pr/release/cli.rb
- spec/git/pr/release/cli_spec.rb
Merging PR's description create a lot of duplication when customizing templates.
Especially if I'm using checkboxes for work procedure manual instead of a list of PRs.
> Add overwrite-description option

- lib/git/pr/release/util.rb
- spec/git/pr/release_spec.rb
@onk @motemen
Hello,
I have discovered that unintended behavior occurs during the big bang release typically seen in the early stages of repository setup.
Due to the checkbox state verification being based on a prefix match of the PR number, when multiple PRs are included, checkboxes may be unintentionally marked for PRs that weren't intended.
```
// Old Body
// New Body
// Expected 
// Actual
```
Modify to check for the existence of a space after the PR number.
> Allow big bang release PR
